### ISSUE TITLE
Crashing while running

### ISSUE THREAD

**Issue by AIPTU** [cooldogedev/BedrockEconomy#1]
Crashdump:
[Sun_Sep_5-07.18.14-UTC_2021.log](https://github.com/cooldogedev/BedrockEconomy/files/7111114/Sun_Sep_5-07.18.14-UTC_2021.log)

**Comment by cooldogedev** [comment]
if you're using mysql there's something wrong with your configuration that caused the query to fail and return null, let me know if this bug still occurs

**Comment by AIPTU** [comment]
I just ran it and didn't set any configuration beforehand

**Comment by cooldogedev** [comment]
have you tried running the latest build from poggit?

**Comment by AIPTU** [comment]
Fixed in build https://github.com/cooldogedev/BedrockEconomy/commit/a191109c75f9a6a81b2fa8b9c86c5e8058cf2e73
