### ISSUE TITLE
Composer package

### ISSUE THREAD

**Issue by JaxkDev** [cooldogedev/BedrockEconomy#101]
**Is your feature request related to a problem? Please describe.**
Attempting to include BedrockEconomy as a dependency in another plugins composer dependencies for easy autoloading for phpstan analysis.

**Describe the solution you'd like**
Doesn't have to even be published on packagist, just a basic composer.json file added to repo to allow others to include the plugin (& API) via composer

**Describe alternatives you've considered**
Manually adding git repo and autoload etc (for people looking for ref:)
```
...
    "require-dev": {
        "cooldogepm/bedrockeconomy": "dev-pm5"
    },
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "cooldogepm/bedrockeconomy",
                "version": "dev-pm5",
                "source": {
                    "url": "https://github.com/cooldogepm/BedrockEconomy",
                    "type": "git",
                    "reference": "origin/pm5"
                },
                "autoload": {
                    "psr-4": { "": "src/" }
                }
            }
        }
    ],
```

**Additional context**
None

**Comment by cooldogedev** [comment]
https://github.com/cooldogepm/BedrockEconomy/pull/107
