### ISSUE TITLE
Crash, fix please

### ISSUE THREAD

**Issue by Wayder228** [cooldogedev/BedrockEconomy#105]
Crash on startup, not updated COMMANDOO

Call to a member function getParameters() on array
File: pmsrc/vendor/pocketmine/bedrock-protocol/src/AvailableCommandsPacket
Line: 533
Type: Error
Backtrace:
#0 pmsrc/vendor/pocketmine/bedrock-protocol/src/DataPacket(84): pocketmine\network\mcpe\protocol\AvailableCommandsPacket->encodePayload(object pocketmine\network\mcpe\protocol\serializer\PacketSerializer#141022)
#1 pmsrc/src/network/mcpe/NetworkSession(489): pocketmine\network\mcpe\protocol\DataPacket->encode(object pocketmine\network\mcpe\protocol\serializer\PacketSerializer#141022)
#2 pmsrc/src/network/mcpe/NetworkSession(470): pocketmine\network\mcpe\NetworkSession::encodePacketTimed(object pocketmine\network\mcpe\protocol\serializer\PacketSerializer#141022, object pocketmine\network\mcpe\protocol\AvailableCommandsPacket#140978)
#3 plugins/RankSystem_dev-71.phar/src/IvanCraft623/RankSystem/libs/CortexPE/Commando/PacketHooker(81): pocketmine\network\mcpe\NetworkSession->sendDataPacket(object pocketmine\network\mcpe\protocol\AvailableCommandsPacket#140978)
#4 plugins/RankSystem_dev-71.phar/src/IvanCraft623/RankSystem/libs/CortexPE/Commando/libs/muqsit/simplepackethandler/interceptor/PacketInterceptorListener(83): IvanCraft623\RankSystem\libs\CortexPE\Commando\PacketHooker::IvanCraft623\RankSystem\libs\CortexPE\Commando\{closure}(object pocketmine\network\mcpe\protocol\AvailableCommandsPacket#140978, object pocketmine\network\mcpe\NetworkSession#166449)
#5 pmsrc/src/event/RegisteredListener(61): IvanCraft623\RankSystem\libs\CortexPE\Commando\libs\muqsit\simplepackethandler\interceptor\PacketInterceptorListener->IvanCraft623\RankSystem\libs\CortexPE\Commando\libs\muqsit\simplepackethandler\interceptor\{closure}(object pocketmine\event\server\DataPacketSendEvent#141441)
#6 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketSendEvent#141441)
#7 pmsrc/src/network/mcpe/NetworkSession(463): pocketmine\event\Event->call()
#8 plugins/EnderChest.phar/src/fernanACM/EnderChest/libs/CortexPE/Commando/PacketHooker(81): pocketmine\network\mcpe\NetworkSession->sendDataPacket(object pocketmine\network\mcpe\protocol\AvailableCommandsPacket#140978)
#9 plugins/EnderChest.phar/src/fernanACM/EnderChest/libs/CortexPE/Commando/libs/muqsit/simplepackethandler/interceptor/PacketInterceptorListener(83): fernanACM\EnderChest\libs\CortexPE\Commando\PacketHooker::fernanACM\EnderChest\libs\CortexPE\Commando\{closure}(object pocketmine\network\mcpe\protocol\AvailableCommandsPacket#140978, object pocketmine\network\mcpe\NetworkSession#166449)
#10 pmsrc/src/event/RegisteredListener(61): fernanACM\EnderChest\libs\CortexPE\Commando\libs\muqsit\simplepackethandler\interceptor\PacketInterceptorListener->fernanACM\EnderChest\libs\CortexPE\Commando\libs\muqsit\simplepackethandler\interceptor\{closure}(object pocketmine\event\server\DataPacketSendEvent#141449)
#11 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketSendEvent#141449)
#12 pmsrc/src/network/mcpe/NetworkSession(463): pocketmine\event\Event->call()
#13 plugins/BedrockEconomy.phar/src/cooldogedev/BedrockEconomy/libs/CortexPE/Commando/PacketHooker(81): pocketmine\network\mcpe\NetworkSession->sendDataPacket(object pocketmine\network\mcpe\protocol\AvailableCommandsPacket#140978)
#14 plugins/BedrockEconomy.phar/src/cooldogedev/BedrockEconomy/libs/CortexPE/Commando/libs/muqsit/simplepackethandler/interceptor/PacketInterceptorListener(83): cooldogedev\BedrockEconomy\libs\CortexPE\Commando\PacketHooker::cooldogedev\BedrockEconomy\libs\CortexPE\Commando\{closure}(object pocketmine\network\mcpe\protocol\AvailableCommandsPacket#140978, object pocketmine\network\mcpe\NetworkSession#166449)
#15 pmsrc/src/event/RegisteredListener(61): cooldogedev\BedrockEconomy\libs\CortexPE\Commando\libs\muqsit\simplepackethandler\interceptor\PacketInterceptorListener->cooldogedev\BedrockEconomy\libs\CortexPE\Commando\libs\muqsit\simplepackethandler\interceptor\{closure}(object pocketmine\event\server\DataPacketSendEvent#187728)
#16 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketSendEvent#187728)
#17 pmsrc/src/network/mcpe/NetworkSession(463): pocketmine\event\Event->call()
#18 pmsrc/src/network/mcpe/NetworkSession(993): pocketmine\network\mcpe\NetworkSession->sendDataPacket(object pocketmine\network\mcpe\protocol\AvailableCommandsPacket#140978)
#19 pmsrc/src/network/mcpe/handler/PreSpawnPacketHandler(126): pocketmine\network\mcpe\NetworkSession->syncAvailableCommands()
#20 pmsrc/src/network/mcpe/NetworkSession(325): pocketmine\network\mcpe\handler\PreSpawnPacketHandler->setUp()
#21 pmsrc/src/network/mcpe/NetworkSession(810): pocketmine\network\mcpe\NetworkSession->setHandler(object pocketmine\network\mcpe\handler\PreSpawnPacketHandler#147724)
#22 pmsrc/src/network/mcpe/NetworkSession(276): pocketmine\network\mcpe\NetworkSession->beginSpawnSequence()
#23 pmsrc/src/promise/Promise(45): pocketmine\network\mcpe\NetworkSession->onPlayerCreated(object pocketmine\player\Player#148552)
#24 pmsrc/src/network/mcpe/NetworkSession(239): pocketmine\promise\Promise->onCompletion(object Closure#188711, object Closure#148534)
#25 pmsrc/src/network/mcpe/NetworkSession(805): pocketmine\network\mcpe\NetworkSession->createPlayer()
#26 pmsrc/src/network/mcpe/handler/ResourcePacksPacketHandler(142): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
#27 pmsrc/vendor/pocketmine/bedrock-protocol/src/ResourcePackClientResponsePacket(61): pocketmine\network\mcpe\handler\ResourcePacksPacketHandler->handleResourcePackClientResponse(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket#148697)
#28 pmsrc/src/network/mcpe/NetworkSession(438): pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket->handle(object pocketmine\network\mcpe\handler\ResourcePacksPacketHandler#188707)
#29 pmsrc/src/network/mcpe/NetworkSession(382): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket#148697, string[4] ....)
#30 pmsrc/src/network/mcpe/raklib/RakLibInterface(218): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[7] c.`a`..)
#31 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[16] .....G.8.......[)
#32 pmsrc/src/network/mcpe/raklib/RakLibInterface(110): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#192349)
#33 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#34 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
#35 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#36 pmsrc/src/Server(1690): pocketmine\snooze\SleeperHandler->sleepUntil(float 1692977503.7919)
#37 pmsrc/src/Server(1064): pocketmine\Server->tickProcessor()
#38 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[13] /root/Server/, string[21] /root/Server/plugins/)
#39 pmsrc/src/PocketMine(357): pocketmine\server()
#40 pmsrc(11): require(string[57] phar:///root/Server/PocketMine-MP.phar/src/PocketMine.php)

**Comment by cooldogedev** [comment]
Use the latest version
