### ISSUE TITLE
Error that appears when paying players who are offline

### ISSUE THREAD

**Issue by AraaCuteUwU** [cooldogedev/BedrockEconomy#113]
[Thu_Oct_19-16.19.08-AWST_2023.log](https://github.com/cooldogepm/BedrockEconomy/files/13039871/Thu_Oct_19-16.19.08-AWST_2023.log)

**Comment by cooldogedev** [comment]
Fixed by https://github.com/cooldogepm/BedrockEconomy/commit/1463a400743ad4a1fc0209b9123775aeee5746cf
