### ISSUE TITLE
Balance becomes negative when using CLOSURE()->subtract

### ISSUE THREAD

**Issue by minijaham** [cooldogedev/BedrockEconomy#114]
Not sure if this is only me, but using `BedrockEconomyAPI::CLOSURE()->subtract()` with bigger amount than the player's balance makes their balance negative, instead of firing InsufficientFundsException.

Confirmed that this is happening on dev-93 - 88. Probably also happens on lower builds as well.

**Comment by minijaham** [comment]
Just confirmed that even when my balance is negative, I'm able to use /pay and other commands.

Currently on PM 5.8.1

**Comment by minijaham** [comment]
Doesn't happen on latest release.

**Comment by cooldogedev** [comment]
What data provider were you using?

**Comment by minijaham** [comment]
> What data provider were you using?

Sqlite

**Comment by cooldogedev** [comment]
I've just tested it and it seems like I can't reproduce it, can you try this [build](https://poggit.pmmp.io/r/228247/BedrockEconomy_dev-95.phar)

**Comment by minijaham** [comment]
> I've just tested it and it seems like I can't reproduce it, can you try this [build](https://poggit.pmmp.io/r/228247/BedrockEconomy_dev-95.phar)

Hmm, then it could probably be just me. It's still happening on my end.

**Comment by cooldogedev** [comment]
Can you send me both your config and database file (`players.db`) on Discord @cooldogedev
