### ISSUE TITLE
The plugin crashes my server :(

### ISSUE THREAD

**Issue by Ratioxddd** [cooldogedev/BedrockEconomy#119]
When i try to enter the server it kicks me out and stops the server,the error says "Call to a member function getParameters() on array"
https://crash.pmmp.io/view/9994276 Here is the dump
![image](https://github.com/cooldogepm/BedrockEconomy/assets/155786666/153798de-cdc9-45ec-a8ec-a749312690b1)

**Comment by cooldogedev** [comment]
Looks like you're using an outdated version  (v2.1.1) of BedrockEconomy, use the latest [release](https://poggit.pmmp.io/p/BedrockEconomy/2.1.2) (v2.1.2) from poggit
