### ISSUE TITLE
If transaction takes balance <0, bedrock eco gets mad?

### ISSUE THREAD

**Issue by n00bslayr94** [cooldogedev/BedrockEconomy#120]
[Wed_Jan_10-21.52.28-GMT_2024.log](https://github.com/cooldogepm/BedrockEconomy/files/13894902/Wed_Jan_10-21.52.28-GMT_2024.log)

**Comment by cooldogedev** [comment]
Looks like you're using an outdated version of BedrockEconomy, use the [dev build](https://poggit.pmmp.io/ci/cooldogepm/BedrockEconomy/BedrockEconomy/dev:107)
