### ISSUE TITLE
getAPI got removed?

### ISSUE THREAD

**Issue by Terpz710** [cooldogedev/BedrockEconomy#122]
$this->eco->getAPI()->addToPlayerBalance($player->getName(), (int) ceil($amount), ClosureContext::create(static function(bool $success) use($callback) : void {
                    $callback($success);
                    

so “getAPI” doesn’t exist no more what was the chnages made?

**Comment by cooldogedev** [comment]
Use the [BedrockEconomyAPI](https://github.com/cooldogepm/BedrockEconomy/blob/pm5/src/cooldogedev/BedrockEconomy/api/BedrockEconomyAPI.php#L66) class to access the API you want to use, if you used `getAPI` then it means you're using the Legacy API
