### ISSUE TITLE
BedrockEconomy requires xbox authentication.

### ISSUE THREAD

**Issue by LinQu** [cooldogedev/BedrockEconomy#123]
i user waterdogpe proxy and in server server.properties xba is off and then crash get message " BedrockEconomy requires xbox authentication.", if i change xba on get no authentication why?
hwo to solve help me
thanks

**Comment by SkulZOnTheYT** [comment]
> i user waterdogpe proxy and in server server.properties xba is off and then crash get message " BedrockEconomy requires xbox authentication.", if i change xba on get no authentication why? hwo to solve help me thanks

use bedrock economy version below version 4

**Comment by cooldogedev** [comment]
Enable login extras in WDPE and use this [plugin](https://github.com/cooldogepm/WDPELoginExtras)

**Comment by cooldogedev** [comment]
Duplicate of https://github.com/cooldogepm/BedrockEconomy/issues/115
