### ISSUE TITLE
Crash on latest poggit release

### ISSUE THREAD

**Issue by n00bslayr94** [cooldogedev/BedrockEconomy#124]
Doesn’t happen on dev-107 version. 
Running PM 5.12.0.

[Mon_Mar_11-20.37.29-GMT_2024.log](https://github.com/cooldogepm/BedrockEconomy/files/14570996/Mon_Mar_11-20.37.29-GMT_2024.log)

**Comment by cooldogedev** [comment]
Submitted a new release
