### ISSUE TITLE
Add the Spanish language to the plugin

### ISSUE THREAD

**Issue by vJorgee** [cooldogedev/BedrockEconomy#126]
Hello! I've translated the plugin into Spanish. Here is the file named "es-ES" 
I upload the file as a txt file because i cant upload the yml file.
Have a great day!

[es-ES.txt](https://github.com/cooldogepm/BedrockEconomy/files/14653109/es-ES.txt)

**Comment by TrinitroToluen0** [comment]
Para esa traducción mejor no hagas nada
