### ISSUE TITLE
Add composer json

### ISSUE THREAD

**Issue by AIPTU** [cooldogedev/BedrockEconomy#14]
As the title say

**Comment by KygekDev** [comment]
> As the title say

@AIPTU why do you think this plugin needs composer.json?

**Comment by AIPTU** [comment]
Since this plugin has not been released to poggit, I use composers as a substitute for poggit to test some plugins that require dependency with this plugin.

**Comment by KygekDev** [comment]
> Since this plugin has not been released to poggit, I use composers as a substitute for poggit to test some plugins that require dependency with this plugin.

I see, but if I be you, I would clone the GitHub repository and add it in my IDE's external libraries instead. If I need to update my repository clone, I can simply run `git pull` inside the directory.

**Comment by cooldogedev** [comment]
The plugin has been already submitted to Poggit, it's now up for the reviewers to decide whether to approve it or not.

**Comment by cooldogedev** [comment]
looks like the plugin isn't getting approved, it's been on queue for a while now.
