### ISSUE TITLE
eliminate usages of XUID

### ISSUE THREAD

**Issue by cooldogedev** [cooldogedev/BedrockEconomy#15]
xuid isn't usable when online mode is disabled

**Comment by KygekDev** [comment]
Then what to use instead?

**Comment by cooldogedev** [comment]
> Then what to use instead?

Xuids don't work for offline mode, unique ids is an alternative. UUIDs for online mode is based on the players xuid so it is guaranteed to be unique, for offline players it generates one based on their username if i recall correctly.

**Comment by cooldogedev** [comment]
closed in https://github.com/cooldogedev/BedrockEconomy/commit/0eb191492cb8dd15c54fa6fc6d573de70fcba303
