### ISSUE TITLE
using mysql or sqlite is not recommended

### ISSUE THREAD

**Issue by theohdg2** [cooldogedev/BedrockEconomy#24]
using sql to make an economy plugin is very unsuitable and will really lag your server a lot for nothing so I advise you to put the db in json or yml (preferably json) if people want to make a system of economy inter server why not make a plugin that will take care of it and suddenly will be able to attract more people because people who want to do just a server can do it without having to make db and those who want can do it just by installing a " extension" which will do it automatically

**Comment by theohdg2** [comment]
Yes I'm very serious but don't take it the wrong way why attack me when I'm just telling you that sql takes longer to run than config via a file after again I just said it's not recommended but actually works just with experience (core of a server) I'm telling you that sql takes too much time and is not suitable for minecraft but I'll let you do what you want!

**Comment by OctoPussh** [comment]
You better close this and stop embarrassing yourself, pro tip: Do some more research, analyze things so you don't look stupid

**Comment by theohdg2** [comment]
tell me how sql is faster than a file modification

**Comment by ethaniccc** [comment]
Queries can be done asynchronously - they don't need to be done on the main thread. There's not going to be lag because those queries are done asynchronously.

**Comment by OctoPussh** [comment]
> Indeed if the requests are carried out in an asynchronous way there will be no lag but in any case as I directly said it is a recommendation and not an obligation but if the server does not have enough thread which happens very very very rarely without lying I find a shame to have to open a thread just to have to make requests

You need to study more dude. I/O operations can also block the main thread. Accept that you were wrong.
