### ISSUE TITLE
problem continues

### ISSUE THREAD

**Issue by SrBanYT2143** [cooldogedev/BedrockEconomy#26]
Same problem continues.

**Comment by SrBanYT2143** [comment]
Same mistake

**Comment by SrBanYT2143** [comment]
PocketMine-MP Crash Dump Tue Feb 15 16:48:54 -03 2022

Error: Object of type Volatile is not callable
File: plugins/BedrockEconomy-main.phar/src/cooldogedev/libSQL/ConnectionPool
Line: 163
Type: Error

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: BedrockEconomy

Code:
[154]                 $freeThread = $thread;
[155]                 break;
[156]             }
[157] 
[158]             if (!$freeThread) {
[159]                 $freeThread = $thread;
[160]                 continue;
[161]             }
[162] 
[163]             if (count($freeThread->getQueries()) > count($thread->getQueries()())) {
[164]                 $freeThread = $thread;
[165]             }
[166]         }
[167] 
[168]         return $freeThread;
[169]     }
[170] 
[171]     /**
[172]      * @return SQLThread[]
[173]      */

Backtrace:
#0 plugins/BedrockEconomy-main.phar/src/cooldogedev/libSQL/ConnectionPool(136): cooldogedev\libSQL\ConnectionPool->getFreeThread()
#1 plugins/BedrockEconomy-main.phar/src/cooldogedev/BedrockEconomy/account/AccountManager(90): cooldogedev\libSQL\ConnectionPool->submit(object cooldogedev\BedrockEconomy\query\sqlite\player\SQLitePlayerRetrievalQuery#108254, string[15] bedrock_economy, object cooldogedev\libSQL\context\ClosureContext#108332)
#2 plugins/BedrockEconomy-main.phar/src/cooldogedev/BedrockEconomy/api/BedrockEconomyAPI(158): cooldogedev\BedrockEconomy\account\AccountManager->getBalance(string[9] ManoNicky, object cooldogedev\libSQL\context\ClosureContext#108332)
#3 plugins/BedAPIScore/src/Jonas/BedAPIScore/listeners/EventListener(35): cooldogedev\BedrockEconomy\api\BedrockEconomyAPI->getPlayerBalance(string[9] ManoNicky, object cooldogedev\libSQL\context\ClosureContext#108332)
#4 pmsrc/src/event/RegisteredListener(75): Jonas\BedAPIScore\listeners\EventListener->onMoneyChange(object cooldogedev\BedrockEconomy\event\TransactionSubmitEvent#108255)
#5 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object cooldogedev\BedrockEconomy\event\TransactionSubmitEvent#108255)
#6 plugins/BedrockEconomy-main.phar/src/cooldogedev/BedrockEconomy/api/BedrockEconomyAPI(124): pocketmine\event\Event->call()
#7 plugins/BedrockEconomy-main.phar/src/cooldogedev/BedrockEconomy/command/PayCommand(141): cooldogedev\BedrockEconomy\api\BedrockEconomyAPI->addToPlayerBalance(string[9] ManoNicky, integer 99)
#8 plugins/BedrockEconomy-main.phar/src/cooldogedev/libSQL/context/ClosureContext(99): cooldogedev\BedrockEconomy\command\PayCommand->cooldogedev\BedrockEconomy\command\{closure}(integer 2992292, object Closure#108262)
#9 plugins/BedrockEconomy-main.phar/src/cooldogedev/libSQL/ConnectionPool(89): cooldogedev\libSQL\context\ClosureContext->invoke(integer 2992292)
#10 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): cooldogedev\libSQL\ConnectionPool->cooldogedev\libSQL\{closure}()
#11 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
#12 pmsrc/src/Server(1660): pocketmine\snooze\SleeperHandler->sleepUntil(double 1644954534.7447)
#13 pmsrc/src/Server(1046): pocketmine\Server->tickProcessor()
#14 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[46] /home/minecraft/multicraft/servers/server2180/, string[54] /home/minecraft/multicraft/servers/server2180/plugins/)
#15 pmsrc/src/PocketMine(327): pocketmine\server()
#16 pmsrc(11): require(string[87] phar:///home/minecraft/multicraft/servers/server2180/1.18-4.2.0.phar/src/PocketM)

**Comment by cooldogedev** [comment]
try the latest build, https://poggit.pmmp.io/ci/cooldogedev/BedrockEconomy/BedrockEconomy
