### ISSUE TITLE
questen

### ISSUE THREAD

**Issue by FlxiBoy1313** [cooldogedev/BedrockEconomy#33]
Hey, 
Ehm one last question, when I do this, it always comes out as 0, is there another possibility? Have already tried with $end = 0, $end = $balance, return $end doesn't work either.

```php
        BedrockEconomyAPI::getInstance()->getPlayerBalance(
            strtolower($player->getName()),
            ClosureContext::create(
                function (?int $balance) {
                    return $balance;
                },
            )
        );
        return 0;
```

**Comment by cooldogedev** [comment]
Because that's not how asynchronous programming work

**Comment by cooldogedev** [comment]
it'll always return zero because the return statement from the closure will return that in its own function context

**Comment by FlxiBoy1313** [comment]
okay thx
