### ISSUE TITLE
error

### ISSUE THREAD

**Issue by GamerMJay** [cooldogedev/BedrockEconomy#34]
[16:57:48.900] [Server thread/CRITICAL]: UnhandledMatchError: "Unhandled match value of type string" (EXCEPTION) in "plugins/BedrockEconomy.phar/src/cooldogedev/BedrockEconomy/BedrockEconomy" at line 123

--- Stack trace ---

#0 (): cooldogedev\BedrockEconomy\BedrockEconomy->cooldogedev\BedrockEconomy\{closure}(array[4])

#1 plugins/BedrockEconomy.phar/src/cooldogedev/BedrockEconomy/BedrockEconomy(122): array_map(object Closure#100285, array[7])

#2 plugins/BedrockEconomy.phar/src/cooldogedev/BedrockEconomy/BedrockEconomy(99): cooldogedev\BedrockEconomy\BedrockEconomy->initializeCommands()

#3 pmsrc/src/plugin/PluginBase(137): cooldogedev\BedrockEconomy\BedrockEconomy->onEnable()

#4 pmsrc/src/plugin/PluginManager(437): pocketmine\plugin\PluginBase->onEnableStateChange(true)

#5 pmsrc/src/Server(1385): pocketmine\plugin\PluginManager->enablePlugin(object cooldogedev\BedrockEconomy\BedrockEconomy#101592)

#6 pmsrc/src/Server(1011): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#24932)

#7 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/minecraft/, string[24] /home/minecraft/plugins/)

#8 pmsrc/src/PocketMine(327): pocketmine\server()

#9 pmsrc(11): require(string[57] phar:///home/minecraft/pocketmine.phar/src/PocketMine.php)

--- End of exception information ---

**Comment by cooldogedev** [comment]
looks like you have some kind of corrupted language file

**Comment by GamerMJay** [comment]
my commands:

commands:
  balance:
    name: coins
    description: Schaue deine Coins an
    usage: "&cHilfe /balance [player: string]"
    aliases: [ ]
  pay:
    name: pay
    description: Überweise jemanden Coins
    usage: "&cHilfe /pay (spieler) (anzahl)"
    aliases: [ ]
  top-balance:
    name: topmoney
    description: Schaue dir die Top Coins an
    usage: "&cHilfe /topbalance [page: number]"
    aliases: [ ]
  add-balance:
    name: addcoins
    description: Gebe jemanden Coins dazu
    usage: "&cHilfe /addbalance [player: string] <amount: number>"
    aliases: [ ]
  remove-balance:
    name: removebalance
    description: Entferne Coins bei jemanden
    usage: "&cHilfe /removebalance [player: string] <amount: number>"
    aliases: [ ]
  set-balance:
    name: setmoney
    description: Setzte Coins
    usage: "&cHilfe /setbalance [player: string] <amount: number>"
    aliases: [ ]
  delete-account:
    name: deleteaccount
    description: Deletes an account of a user
    usage: "&cUsage /deleteaccount [player: string]"
    aliases: [ ]

**Comment by GamerMJay** [comment]
the messages have no problem

**Comment by cooldogedev** [comment]
closing in favor of https://github.com/cooldogedev/BedrockEconomy/commit/42061117e00b3a29335ffc4f62a7b51ec5586f7b
