### ISSUE TITLE
no work

### ISSUE THREAD

**Issue by DimonYoing** [cooldogedev/BedrockEconomy#55]
Console error, but the virions are in the folder, why the error ?

**Comment by cooldogedev** [comment]
what's the error

**Comment by reyyan987** [comment]
@DimonYoing pls send the error log

**Comment by DimonYoing** [comment]
Everything worked, it was necessary to download via phar file

**Comment by DimonYoing** [comment]
And what other boards does it support?

**Comment by DimonYoing** [comment]
And add another so that you can not enter the full nickname, for example, I am MrAizex "/addbalance MrA 5000" so that the system recognizes the player by INCOMPLETE spelling of the nickname

**Comment by cooldogedev** [comment]
> And add another so that you can not enter the full nickname, for example, I am MrAizex "/addbalance MrA 5000" so that the system recognizes the player by INCOMPLETE spelling of the nickname

it already does that for online player however it doesn't have command autofill

**Comment by cooldogedev** [comment]
> Does this economy support scorehud?

yes, https://github.com/cooldogedev/BedrockEconomy/blob/main/src/cooldogedev/BedrockEconomy/addon/scorehud/ScoreHudAddon.php#L38-#L41

**Comment by cooldogedev** [comment]
please don't create an issue without elaboration and don't use one issue for multiple purposes.
