### ISSUE TITLE
API proposal

### ISSUE THREAD

**Issue by cooldogedev** [cooldogedev/BedrockEconomy#6]
implement a more simplified API for plugin developers or maybe just use singleton for the main class

**Comment by SOF3** [comment]
Since you're doing singleton anyway, why not just make all the API methods static?

**Comment by cooldogedev** [comment]
> Since you're doing singleton anyway, why not just make all the API methods static?

The reason behind that is i was trying to not violate OOP as much as I could. I'm thinking of having an API entry/class (wrapper for the existing methods) to use static methods.

**Comment by SOF3** [comment]
Using static methods doesn't violate OOP.

I mean, if you want to keep the API simple, simply expose a static method and fetch the singleton inside the implementation.

**Comment by SOF3** [comment]
Any updates?

This plugin will likely get featured on Poggit only if it has a proper, simple API intended for external users.

**Comment by cooldogedev** [comment]
> Any updates?
> 
> This plugin will likely get featured on Poggit, but only if it has a proper, simple API intended for external users.

Yeah there is update on my local machine, I'll push them after doing some final testing tonight.

**Comment by cooldogedev** [comment]
https://github.com/cooldogedev/BedrockEconomy/commit/8ce1f9b4363f38c15841c39b5e73e47cba38c05f has introduced the following [class](https://github.com/cooldogedev/BedrockEconomy/blob/main/src/cooldogedev/BedrockEconomy/api/BedrockEconomyAPI.php) it is the simplified version of the API for plugin developers.
