### ISSUE TITLE
Scorehud support

### ISSUE THREAD

**Issue by MrBlasyMSK** [cooldogedev/BedrockEconomy#61]
**Is your feature request related to a problem? Please describe.**
-
It would be nice to have support for Scorehud, a lot of people would use it

**Describe the solution you'd like**
-
I leave here the EconomyAPI ZIP file, with this you can guide you on how to do it
[EcoAPIscore.zip](https://github.com/cooldogedev/BedrockEconomy/files/8244592/EcoAPIscore.zip)

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by fadheldev** [comment]
Already exists, https://github.com/cooldogedev/BedrockEconomy#scorehud-integration
