### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by creeperplayer20** [cooldogedev/BedrockEconomy#64]
Hello, I'm trying to get player money by using your API and it's very confusing. I have $100 (balance), but in my GUI it shows that I have $0.

>              BedrockEconomyAPI::getInstance()->getPlayerBalance(
>                 "$username",
>                 ClosureContext::create(
>                     function (?int $balance): void {
>                         22 => VanillaItems::WRITABLE_BOOK()->setCustomName("§r§7My Info§f\nBalance§7: §2$ §f" . $balance),
>                     },
>                 )
>             );

**Comment by fadheldev** [comment]
This code seems to be working just fine. (using the new API)

```php
    public function onPlayerJoin(PlayerJoinEvent $event): void
    {
        $player = $event->getPlayer();

        BedrockEconomyAPI::beta()->get($player->getName())
            ->onCompletion(
                function (int $balance) use ($player): void {
                    $player->getInventory()->setItemInHand(VanillaItems::WRITABLE_BOOK()->setCustomName("§r§7My Info§f\nBalance§7: §2$ §f" . $balance));
                },
                function () use ($player): void {
                    $player->sendMessage("§cSomething went wrong while loading your balance");
                }
            );
    }
```
