### ISSUE TITLE
ScoreHud implementation

### ISSUE THREAD

**Issue by TukangM** [cooldogedev/BedrockEconomy#72]
https://github.com/Ifera/ScoreHudX/issues/26

EconomyAPI users want to use BedrockEconomy money info on ScoreHud and such
![image](https://user-images.githubusercontent.com/91467886/161778686-1a7d0cbe-0044-4e02-82c7-01a6fff80914.png)

**Comment by TukangM** [comment]
> [Ifera/ScoreHudX#26](https://github.com/Ifera/ScoreHudX/issues/26)
> 
> EconomyAPI users want to use BedrockEconomy money info on ScoreHud and such ![image](https://user-images.githubusercontent.com/91467886/161778686-1a7d0cbe-0044-4e02-82c7-01a6fff80914.png)

we need a collaborator as soon as possible so that shop, sell land buy, enchant shop, etc are useful because pm4 changes your mind

**Comment by AIPTU** [comment]
https://github.com/cooldogedev/BedrockEconomy#scorehud-integration

**Comment by TukangM** [comment]
> https://github.com/cooldogedev/BedrockEconomy#scorehud-integration

solved... not yet
