### ISSUE TITLE
Proposal: Replace integers with floats

### ISSUE THREAD

**Issue by MCPEAbdu77** [cooldogedev/BedrockEconomy#83]
Add support for accepting float values to player balance

**Comment by SOF3** [comment]
Floats should never be used for storing player balance. What you want is decimals, not floats. This can be achieved simply by multiplying the number by a constant float when displaying money.

This can be implemented in a similar way as monetary units.

**Comment by SOF3** [comment]
isn't this duplicate of #69 anyway?

**Comment by cooldogedev** [comment]
> isn't this duplicate of #69 anyway?

Yes, it is already mentioned in https://github.com/cooldogedev/BedrockEconomy/issues/76
