### ISSUE TITLE
BedrockEconomyAPI Dosent Support Strings...

### ISSUE THREAD

**Issue by note3crafter** [cooldogedev/BedrockEconomy#85]
It's not possible to load your money balance in a string...

[Server thread/CRITICAL]: Error: "Object of class cooldogedev\BedrockEconomy\query\sqlite\player\SQLiteRetrieveQuery could not be converted to string"

Is there a possibility?

**Comment by cooldogedev** [comment]
If you mean by loading balance in a string, https://github.com/cooldogedev/BedrockEconomy/blob/main/src/cooldogedev/BedrockEconomy/command/BalanceCommand.php#L66-#L90

**Comment by note3crafter** [comment]
Yes, exactly! To enable in my CorePlugin to display it in the scoreboard! Thanks! i will it test later

**Comment by cooldogedev** [comment]
You can use the in-built implementation of Scorehud, [BedrockEconomy#scorehud-integration](https://github.com/cooldogedev/BedrockEconomy#scorehud-integration)
