### ISSUE TITLE
CLI has stopped working

### ISSUE THREAD

**Issue by Gin-NonexistentEntity** [cooldogedev/BedrockEconomy#86]
**Describe the bug**
As soon as I stopped my server, cmd window said that 'Stopping other threads' and a window with title 'CLI has stopped working'.
The cmd window was freezed, I can't did anything.

**To Reproduce**
1. Add BedrockEconomy to plugins folder'...'
2. Start Pocketmine  server'
3. Stop the server by type 'stop' then Enter
4. See essue

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/71365319/208928743-51a90d77-ead8-49a9-915e-edc1b65fa063.png)

**OS and version**
 - Server OS: [Windows 10]
 - PocketMine-MP version [4.12.2]
 - PHP 8.0 
 - Version [2.0.8]

**Additional context**

**Comment by cooldogedev** [comment]
This could be an issue related to libSQL's threads not shutting down properly, which has been addressed by https://github.com/cooldogedev/libSQL/commit/1c5f1f76125c931f8ca020789023dafb66a1dc20, I'll bump the plugin's dependencies to see if that fixes it

**Comment by cooldogedev** [comment]
Could you try the latest [dev build](https://poggit.pmmp.io/ci/cooldogedev/BedrockEconomy/BedrockEconomy/dev:33) on poggit?

**Comment by Gin-NonexistentEntity** [comment]
Thanks!
