### ISSUE TITLE
Feature Request: Transaction History

### ISSUE THREAD

**Issue by AIPTU** [cooldogedev/BedrockEconomy#89]
Transaction History:
Transaction history records the details of financial transactions that occur within the economy system. It provides a chronological record of all the transactions that have taken place, including information such as sender, receiver, currencies involved, amounts transferred, and timestamps.

**Comment by cooldogedev** [comment]
This can be easily supported through a third party plugin using [Transaction events](https://github.com/cooldogepm/BedrockEconomy/tree/pm5/src/cooldogedev/BedrockEconomy/event/transaction)
