### ISSUE TITLE
ScoreHud Tags: Balance not updated when /addbalance (need re-login)

### ISSUE THREAD

**Issue by AraaCuteUwU** [cooldogedev/BedrockEconomy#99]
**Describe the bug**

**To Reproduce**
1. Add balance to players
2. Check balance on scorehud

**Expected behavior**
The balance is updated automatically on scorehud

**Screenshots**

**OS and version (please complete the following information):**
 - Server OS: Windows
 - PocketMine-MP version 5.3.0
 - Version 1.20.10

**Additional context**

**Comment by fadijalal07** [comment]
did u find a fix?
